### ISSUE TITLE
java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal

### ISSUE THREAD

**Issue by jinkerry** [skprasadu/spring-mvc-examples#1]
when run JpaBookRepositoryTest，throw this exception
```
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 87 more
```

the exception disappeared when i add the dependency at pom.xml, 
and all tests passed.
```
        <dependency>
            <groupId>xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
            <version>1.4.01</version>
        </dependency>
```

**Comment by skprasadu** [comment]
Thanks, I will add it in the pom.
